Card issuer service demo app
enesj/card-issuer-service pull request #1
Opened 2022-11-21 19:46 UTC by enesj

**Card issuer service demo app**

Bekend is implemented with Jetty web server, Reiitit router and Postgresql as db. I am using an embedded version of Postgresql to enable running the app with only one command, with no need for Docker or local installation.

Withdraw and Transfer requests will be rolled back when the balance is negative using `next.jdbc/with-transaction` macro.
Notifications are saved as files in the `resources/notification` folder. Every notification file name begins with time-stamp plus random int because in tests time-stipe is usually the same for all files.

In addition to the authorization endpoint, there are others that maybe can be used if we decide to make a simple frontend for the app.

2022-11-25 00:45 UTC, marcinnowakowskikeeper commented
I have one general comment. My filing is that when you were writing your solution you have tried to imagine, and probably researched, how a third party application which performs authorization for a card issuer can look like and what data like e.g. currencies (to describe amounts), user email (to send notification) it has to process. This was really great.

However I found your approach a bit risky because part of the implementation provided was out of scope of the task even though well implemented. 

Looking at the whole I can give up a little on the main the task which focused on synchronizing transactional and non-transactional resources (in context of authorization processing).

Solution accepted :heavy_check_mark:.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/db.clj
> +   io.zonky.test.db.postgres.embedded.EmbeddedPostgres))
:+1: I really like the idea to configure such a small project / POC with embedded PostgreSQL and not to bother with docker configuration.

A side story I had a small configuration struggle to get https://github.com/zonkyio/embedded-postgres run on my Ubuntu 22.04.1 LTS. After some fiddling with pg_hba.conf I got it going. As always there are pros and cons of a solution.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/db.clj
> +(defonce pg (start-pg!))
I would rather see this call in `app.core` namespace in `-main` function and in parallel in a test utility namespace to ensure that db is running when the whole test suit is executed.

Even in such a small app I would not leave the call in common `db` namespace.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/core.clj
> +  (ring/ring-handler
If already we have this set of routes they could go to a separate namespace `router` or `routes`.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/config.clj
> +(defn deep-merge
This function could be private - defined with e.g. `(defn-`

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/domain/file_notifications.clj
> +(defn get-timestamp
The function could be named `make-notification-file-id` as it is already described in doc string.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/handlers.clj
> +(ns app.handlers
:+1: In bigger app handlers would be split in several namespaces like: `home.handlers`, `user.handers`... and so on but here one namespace is enough.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/handlers.clj
> +(defn response-body
This function could be named `make-add-transaction-response-body` and could be private.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/handlers.clj
> +      (go (send-notification (merge data body)))
I would rather avoid hiding such important business utility in REST response body building function. It would call it directly from the body of function `add-transaction(-handler)`.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/handlers.clj
> +(defn users-handler
I find suffix `-handler` obsolete. All public functions in this namespace are expected to be handlers.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/handlers.clj
> +      (go (send-notification (merge data body)))
:question: Would this implementation with `go` macro be as well correct if we know that it can take really long time / much workload to send single notification and that the number of dispatched notification is significantly big?

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on test/app/core_test.clj
> +(ns app.core-test)
I was expecting to see here the tests described in task definition:

> Please provide tests showing different scenarios. Present at least one scenario where database transaction is broken before it is committed e.g. by programmatically dropping database connection, to show what happens with notification and REST API response in such a case.

2022-11-25 00:46 UTC, marcinnowakowskikeeper commented on src/app/logging.clj
> +                :info ansi/white
:+1:  I found this logging configuration pretty neat ;--D! I like the color settings:

![Screenshot from 2022-11-25 01-42-48](https://user-images.githubusercontent.com/98953679/203879004-aaee1747-b2c9-45ca-8223-cb904c972b9b.png)

2022-11-25 00:51 UTC, marcinnowakowskikeeper requested changes
@enesj The most of the comments are small things except the 2 ones about not following the task description. Last but not least I have just one question which I would like you to answer to complete the code review round: https://github.com/enesj/card-issuer-service/pull/1#discussion_r1031919422

2022-11-27 10:10 UTC, enesj commented on src/app/handlers.clj
> +      (go (send-notification (merge data body)))
I have replaced `core.async.go`  with `core.async.thread`. The problem with `go` is that it is hardcoded to create a maximum of 8 concurrent threads and `thread` **doesn't have this limitation**. Thread is the better approach for heavy-load situations.

2022-11-27 10:28 UTC, enesj commented on test/app/core_test.clj
> +(ns app.core-test)
Created a new [function](https://github.com/enesj/card-issuer-service/blob/e896c0d98b39fd9723cc6724788667e93bc71ee2/src/app/domain/transactions.clj#L96) that programmatically loses connection in the middle of transactions and rolls back the first transaction.
Also created a new [test](https://github.com/enesj/card-issuer-service/blob/e896c0d98b39fd9723cc6724788667e93bc71ee2/test/app/domain/transactions_test.clj#L67) for this functionality.

Similar [functionality](https://github.com/enesj/card-issuer-service/blob/e896c0d98b39fd9723cc6724788667e93bc71ee2/src/app/domain/transactions.clj#L137) was previously created for [withdraw](https://github.com/enesj/card-issuer-service/blob/e896c0d98b39fd9723cc6724788667e93bc71ee2/test/app/domain/transactions_test.clj#L59) and [transfer](https://github.com/enesj/card-issuer-service/blob/e896c0d98b39fd9723cc6724788667e93bc71ee2/test/app/domain/transactions_test.clj#L96) functions in cases where balance was negative after the first transaction.

2022-11-27 10:33 UTC, enesj commented on src/app/db.clj
> +   io.zonky.test.db.postgres.embedded.EmbeddedPostgres))
Maybe this can be resolved by adding [binaries](https://github.com/zonkyio/embedded-postgres-binaries) for a different operating system in deps.edn. I will try this solution, but at the time of making this had access only to MacOs.

2022-11-30 10:45 UTC, marcinnowakowskikeeper commented on src/app/handlers.clj
> +      (go (send-notification (merge data body)))
Thanks for addressing this issue. This exactly what I wanted to hear.

2022-11-30 10:45 UTC, marcinnowakowskikeeper approved these changes

2023-02-14 09:38 UTC, merged